CREATE DATABASE LunaParkMadhouse
USE LunaParkMadhouse

CREATE TABLE Ticket(
TICKETID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SINGLEPRICE DECIMAL(6,3) NOT NULL,
[STATUSID] INT NOT NULL,
ATTRACTIONID INT NOT NULL,
[EVENTID] INT NOT NULL
)

CREATE TABLE [STATUS](
[STATUSID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
STATUSLABEL NVARCHAR(20) NOT NULL
)

ALTER TABLE [STATUS]
ADD CONSTRAINT FK_STATUSID
FOREIGN KEY ([STATUSID]) REFERENCES Ticket(TICKETID)

CREATE TABLE VISITOR(
VISITORID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
VISITORNUMBER INT NOT NULL,
YEARS INT NOT NULL,
[WEIGHT] INT NOT NULL,
HEIGHT  DECIMAL(3,2) NOT NULL
)

CREATE TABLE ATTRACTION(
ATTRACTIONID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
YEARSCONSTRAINT TEXT NOT NULL,
WEIGHTCONSTRAINT TEXT NOT NULL,
HEIGHTCONSTRAINT TEXT NOT NULL,
[DESCRIPTION] TEXT NOT NULL
)

ALTER TABLE ATTRACTION
ADD CONSTRAINT FK_ATTRACTIONID
FOREIGN KEY (ATTRACTIONID) REFERENCES Ticket(TICKETID)

CREATE TABLE DISH(
DISHID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
SINGLEPRICE DECIMAL(4,2) NOT NULL,
[DESCRIPTION] TEXT NOT NULL,
CANTEENID INT NOT NULL
)

CREATE TABLE DRINK(
DRINKID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
BRAND  NVARCHAR(20) NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
SINGLEPRICE DECIMAL(4,2) NOT NULL,
CANTEENID INT NOT NULL
)

CREATE TABLE CANTEEN(
CANTEENID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
[DESCRIPTION] TEXT NOT NULL,
[DATE] DATETIME NOT NULL,
DAYILYPROFIT DECIMAL(6,3) NOT NULL
)

ALTER TABLE CANTEEN
ADD CONSTRAINT FK_CANTEENID
FOREIGN KEY (CANTEENID) REFERENCES DISH(DISHID)

ALTER TABLE CANTEEN
ADD CONSTRAINT FK_DRINKCANTEENID
FOREIGN KEY (CANTEENID) REFERENCES DRINK(DRINKID)

CREATE TABLE SERVANT(
SERVANTID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
CANTEENID INT NOT NULL,
POSITIONID INT NOT NULL
)

ALTER TABLE CANTEEN
ADD CONSTRAINT FK_SERVANTCANTEENID
FOREIGN KEY (CANTEENID) REFERENCES SERVANT(SERVANTID)

CREATE TABLE POSITION(
POSITIONID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NAME] NVARCHAR(20) NOT NULL,
WORKINGHOURSID INT NOT NULL
)

ALTER TABLE POSITION
ADD BONUSFORPOSITION DECIMAL(6,3) NOT NULL

CREATE TABLE WORKINGHOURS(
WORKINGHOURSID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[HOURS]  INT NOT NULL,
SALARY DECIMAL(6,3) NOT NULL
)

ALTER TABLE WORKINGHOURS
ADD CONSTRAINT FK_WORKINGHOURSID
FOREIGN KEY (WORKINGHOURSID) REFERENCES POSITION(POSITIONID)

CREATE TABLE DISH_AND_DRINK_SALES(
SALESID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DISHID INT NOT NULL,
DRINKID INT NOT NULL,
[COUNT] INT NOT NULL
)

CREATE TABLE TICKETSALES(
SALESID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TICKETID INT NOT NULL,
[COUNT] INT NOT NULL
)

ALTER TABLE DISH
ADD CONSTRAINT FK_DISHID
FOREIGN KEY (DISHID) REFERENCES DISH_AND_DRINK_SALES(SALESID)

ALTER TABLE DRINK
ADD CONSTRAINT FK_DRINKID
FOREIGN KEY (DRINKID) REFERENCES DISH_AND_DRINK_SALES(SALESID)

ALTER TABLE TICKET
ADD CONSTRAINT FK_TICKETID
FOREIGN KEY (TICKETID) REFERENCES TICKETSALES(SALESID)


CREATE TABLE [EVENT](
[EVENTID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[DATE] DATE NOT NULL,
STARTTIME  TIME NOT NULL,
CLOSINGTIME  TIME NOT NULL,
[DESCRIPTION] TEXT NOT NULL
)

ALTER TABLE TICKET
ADD CONSTRAINT FK_EVENTTICKETID
FOREIGN KEY (TICKETID) REFERENCES [EVENT]([EVENTID])

CREATE TABLE [SERVICE](
SERVICEID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TIME_OF_VERIFICATION TIME NOT NULL,
PROBLEM TEXT NOT NULL,
[DATE] DATE NOT NULL,
SERVISEPRICE DECIMAL(6,3) NOT NULL,
TIME_FOR_PROBLEM INT NOT NULL,
ATTRACTIONID INT NOT NULL
)

ALTER TABLE ATTRACTION
ADD CONSTRAINT FK_SERVICE_ATTRACTIONID
FOREIGN KEY (ATTRACTIONID) REFERENCES [SERVICE](SERVICEID)